apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: PROJECT/IMAGE3
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3001"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
            - name: DB_HOST
              value: postgres-ping-pong-svc.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
                path: /pingpong
                port: 3001
          readinessProbe:
              httpGet:
                  path: /pingpong
                  port: 3001