name: Build and publish application

on:
  push:

jobs:
  build-publish:
    name: Build, Push, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish writer
        run: |-
          docker build --tag "irmindev/log-writer:$GITHUB_SHA" log-output-writer/
          docker push "irmindev/log-writer:$GITHUB_SHA"

      - name: Build and publish log server
        run: |-
          docker build --tag "irmindev/log-output:$GITHUB_SHA" log-server/
          docker push "irmindev/log-output:$GITHUB_SHA"

      - name: Build and publish ping pong app
        run: |-
          docker build --tag "irmindev/ping-pong:$GITHUB_SHA" ping-pong/
          docker push "irmindev/ping-pong:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images
        run: |-
            kustomize edit set image PROJECT/IMAGE1=irmindev/log-output:$GITHUB_SHA
            kustomize edit set image PROJECT/IMAGE2=irmindev/log-writer:$GITHUB_SHA
            kustomize edit set image PROJECT/IMAGE3=irmindev/ping-pong:$GITHUB_SHA

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}